### ISSUE TITLE
Typescript Compatibility

### ISSUE THREAD

**Issue by hiszd** [zentered/auth0-solid-start#12]
I would love to see some compatibility with Typescript in this package. Some of it would just be adding packages like "@types/auth0-js" to the package.

**Comment by PatrickHeneise** [comment]
Could you open a PR with the types? Happy to merge that.

**Comment by MarioSimou** [comment]
I have raised [this PR](https://github.com/zentered/auth0-solid-start/pull/15) to solve this issue
