### ISSUE TITLE
Has this project been abandoned on the eve of the beta release of solid-start

### ISSUE THREAD

**Issue by semiautomatix** [zentered/auth0-solid-start#32]
I've been having a look at this project, and obviously it's wildly out of date with the beta release. Is this due to lack of contributors, or a general pause until initial release?

I think the project has legs and would definitely be a valuable addition.

**Comment by semiautomatix** [comment]
Perhaps the easiest is to fork it and go from there?

**Comment by PatrickHeneise** [comment]
@semiautomatix thanks for the feedback. The project is certainly not abandoned, but I'm waiting for the api to stabilize. The last round was a bit much and it takes time and energy to keep up with all of that.

Happy to merge contributions to get this up-to-date earlier though.
